### ISSUE TITLE
Create completion checkbox functionality

### ISSUE THREAD

**Issue by nbkm8y5** [nbkm8y5/todolistreact#5]

**Comment by nbkm8y5** [comment]
fixed with b13c0ab6a9ce043807996494253bb487210c2e43

**Comment by hfzi** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
TruthReveller, @Andupk, @twopieare, @caleb-vincent, @eheperson, @MaximeFrancoeur, @salpiras, @ra1amx, @yzuyhp, @Herklos, @dmitvitalii, @lcdavison, @askender, @junorouse, @raharjaliu, @nasa-gibbs, @NeoApostol, @tyl12, @bhandras, @nnoori, @xunshuairu, @jorandradefig, @minkikim89, @a-dera, @rkr8, @Hostn4me, @Quakertlist, @GuanlinLee, @lanzhiquan, @elnegrogato, @RayMiles94, @CoderDuMeng, @1208647615, @MeTaNoV, @Ankk98, @amadeobrands, @H13m0n, @ernestofgonzalez, @WhiteWolfdoge, @shangmacun, @canercandan, @maxmersch, @yashelite, @Ast15, @xkey-, @lukababu, @tbfito, @jiangplus, @philosup, @subercui

**Comment by hfzi** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
etemiz, @troyjfarrell, @tjfwalker, @JohnStratoudakis, @awrelll, @cobject, @LucasReSilva, @triplekill, @sebastiencs, @cadomac, @creamjun, @zooty, @chivalry02, @royalaid, @pata00, @darwinshameran, @lbbtc, @cmcdowell03, @pipi-rtq, @prestonvanloon, @YuChangMonster, @lkp0907, @sigtot, @Otero, @yzs981130, @yaoGreat, @hardygege, @latsa, @sony1995b, @hechen0, @ovaistariq, @lwhuang, @bezalel, @higumachan, @avluent, @mingchan88, @tsivkyn, @atypiape, @bytetao, @makramibrahim, @adamskijow, @123Daoxyz, @james-c, @geniusgao, @Korede-TA, @ryjen, @emurmotol, @austonst, @nanmu42, @harryheng
